spring:
  application:
    name: finance
  datasource:
    url: jdbc:postgresql://localhost:5432/finance
    username: test_user
    password: ${DB_PASSWORD:test}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true